config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users, except: [:destroy]
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index] do
    resources :lessons, except: [:destroy, :index]
  end
  resources :words, only: [:index]

  namespace :admin do
    resources :categories
    resources :words, except: [:index, :new, :show]
    resources :users, only: [:index, :destroy]
  end

  resources :users do
    resources :relationships, only: [:index]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/views/static_pages/about.html.erb
<%= provide :title, t("about") %>
<h1><%= t "static_pages_about" %></h1>
<p><%= t "link_about" %></p>

app/views/static_pages/help.html.erb
<%= provide :title, t("help") %>
<h1><%= t "static_pages_help" %></h1>
<p><%= t "link_help" %></p>

app/views/static_pages/home.html.erb
<%= provide :title, t("home") %>
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
    </aside>
    <div class="col-md-3">
      <h1><%= link_to "Words", words_path %></h1>
    </div>
    <div class="col-md-4">
      <h1><%= link_to "Lessons", categories_path %></h1>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t "welcome" %></h1>
    <h2><%= t "announce" %></h2>
    <%= link_to t("sign_up_now"), new_user_path , class: "btn btn-lg btn-primary" %>
  </div>
<% end %>