config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users, except: [:destroy]
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index] do
    resources :lessons, except: [:destroy, :index]
  end
  resources :words, only: [:index]

  namespace :admin do
    resources :categories
    resources :words, except: [:index, :new, :show]
    resources :users, only: [:index, :destroy]
  end

  resources :users do
    resources :relationships, only: [:index]
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category

  has_many :answers, dependent: :destroy
  has_many :user_answers, dependent: :destroy
  has_many :lessons, through: :user_answers

  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: :reject_answers

  validates_presence_of :question
  validate :at_least_one_correct_answer

  scope :all_words, -> (user, category) { where(category_id: category.id) }
  scope :learned, -> (user, category) { joins(:lessons)
    .where(lessons: {user_id: user.id}, category_id: category.id)
    .merge(UserAnswer.correct_user_answers).distinct }
  scope :not_learned, -> (user, category) { where(category_id: category.id)
    .where.not id: Word.learned(user, category) }

  scope :all_words_all_categories, -> (user) {}
  scope :learned_all_categories, -> (user) {joins(:lessons)
    .where(lessons: {user_id: user.id})
    .merge(UserAnswer.correct_user_answers).distinct }
  scope :not_learned_all_categories, -> (user) { where.not id: Word.learned_all_categories(user) }

  private
  def reject_answers (attributed)
    attributed['answer'].blank?
  end

  def at_least_one_correct_answer
    valid = false
    answers.each do |answer|
      valid = answer.is_correct? ? true : valid unless answer.
        marked_for_destruction?
    end
    errors.add :answers, I18n.t("at_least_one_correct_answer") unless valid
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action only: [:edit, :update, :destroy] {
    @word = load_object Word
  }

  def create
    @word = Word.new word_params
    @category = Category.find params[:word][:category_id]
    if @word.save
      flash[:success] = t "word_added"
      redirect_to :back
    else
      flash[:danger] = t "word_add_failed"
      redirect_to :back
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash.now[:success] = t "word_updated"
      redirect_to [:admin, @word.category]
    else
      flash.now[:danger] = t "word_update_failed"
      render :edit
    end
  end

  def destroy
    if @word.destroy
      flash[:success] = t "word_deleted"
    else
      flash[:danger] = t "word_delete_failed"
    end
    redirect_to :back
  end

  private
  def word_params
    params.require(:word).permit :question, :category_id,
      answers_attributes: [:id, :answer, :is_correct, :_destroy]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = Category.all
    @filter_type = params[:filter_type] || Settings.category.filter_type.all_words
    if !params[:category].blank? && !params[:category][:category_id].blank?
      @category = Category.find params[:category][:category_id]
      @words = Word.includes(:answers).send(@filter_type, current_user, @category)
    else
      @filter_type_all_categories = "#{@filter_type}_all_categories"
      @words = Word.includes(:answers).send(@filter_type_all_categories, current_user)
    end
    @words = @words.paginate page: params[:page]
  end
end

app/views/admin/words/_answer_fields.html.erb
<fieldset>
  <div class="row">
    <div class="col-md-10">
      <div class="input-group">
        <span class="input-group-addon">
          <%= f.check_box :is_correct, type: "checkbox" %>
        </span>
        <%= f.text_field :answer, type: "text", class: "form-control" %>
      </div>
    </div>
    <%= f.hidden_field :_destroy, value: "0" %>
    <%= link_to t("remove"), "", class: "label label-danger remove_fields" %>
  </div>
  <br />
</fieldset>

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word] do |f| %>
  <div class="form-group">
    <%= f.hidden_field :category_id, value: @category.id %>

    <%= f.label t "question" %>
    <%= f.text_field :question, class: "form-control" %>

    <%= f.hidden_field :_destroy %>

    <%= f.label t "answers" %>
    <%= f.fields_for :answers do |answers_for_form| %>
      <%= render "admin/words/answer_fields", f: answers_for_form %>
    <% end %>

    <%= link_to_add_fields t("add_answer"), f, :answers %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/words/_word.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= word.question %></div>
  <table class="table">
    <tr>
      <td class="col-md-10"><%= t "choices" %></td>
      <td class="col-md-2"><%= t "correct" %></td>
    </tr>
    <% word.answers.each do |answer| %>
      <tr>
        <td><%= answer.answer %></td>
        <td>
          <% if answer.is_correct %>
            <%= t "yes" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>

  <div class="panel-footer">
    <%= link_to t("edit"), edit_admin_word_path(word),
      class: "btn btn-success" %>
    <%= link_to t("delete"), [:admin, word], method: :delete,
      data: {confirm: t("confirm")}, class: "btn btn-danger" %>
  </div>
</div>

app/views/admin/words/edit.html.erb
<% provide title: @word.category.title %>
<% provide :button_text, t("finish") %>
<h1><%= t "word_update" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @word] do |f| %>
      <div class="form-group">
        <%= f.label t "question" %>
        <%= f.text_field :question, class: "form-control" %>

        <%= f.hidden_field :_destroy %>

        <%= f.label t "answers" %>

        <%= f.fields_for :answers do |answers_for_form| %>
          <%= render "admin/words/answer_fields", f: answers_for_form %>
        <% end %>

        <%= link_to_add_fields t("add_answer"), f, :answers %>
      </div>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>