config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users, except: [:destroy]
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index] do
    resources :lessons, except: [:destroy, :index]
  end
  resources :words, only: [:index]

  namespace :admin do
    resources :categories
    resources :words, except: [:index, :new, :show]
    resources :users, only: [:index, :destroy]
  end

  resources :users do
    resources :relationships, only: [:index]
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "error_messages" %> 
      <%= pluralize object.errors.count, t("error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to user_relationships_path @user, id: :following do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t "following" %>
  <% end %>
  
  <%= link_to user_relationships_path @user, id: :followers do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t "followers" %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to current_user do %>
  <%= gravatar_for current_user %>
  <strong><h1><%= current_user.name %></h1></strong>
<% end %>

app/views/shared/_users.html.erb
<div class="user">
  <%= gravatar_for user, size: Settings.size %>
  <strong>
    <h1><%= link_to user.name, user %></h1>
  </strong>
  <%= link_to t("admin_delete_user"), admin_user_path(user), method: :delete, data: {confirm: t("confirm")} %>
</div>