config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users, except: [:destroy]
  resources :relationships, only: [:create, :destroy]
  resources :categories, only: [:index] do
    resources :lessons, except: [:destroy, :index]
  end
  resources :words, only: [:index]

  namespace :admin do
    resources :categories
    resources :words, except: [:index, :new, :show]
    resources :users, only: [:index, :destroy]
  end

  resources :users do
    resources :relationships, only: [:index]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons, dependent: :destroy
  has_many :user_answers, dependent: :destroy
  has_many :words, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action except: [:index, :new, :create] { 
    @category = load_object Category
  }
  
  def index
    @categories = Category.paginate page: params[:page]
  end
  
  def show
    @word = Word.new
    Settings.word.number_of_answers.times do
      @answer = @word.answers.build
    end
    @words = @category.words.paginate page: params[:page], 
      per_page: Settings.word.per_page
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "category_created"
      redirect_to admin_categories_path
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @category.update_attributes category_params
      flash[:success] = t "category_updated"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end
  
  def destroy
    if @category.destroy
      flash[:success] = t "category_deleted"
    else
      flash[:danger] = t "category_not_deleted"
    end
    redirect_to admin_categories_path
  end
  
  private
  def category_params
    params.require(:category).permit :title, :description, :image
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate page: params[:page]
  end
end

app/views/admin/categories/_category.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3><%= link_to category.title, admin_category_path(category) %></h3>
  </div>
  <div class="panel-body">
    <div><%= category.description %></div>
  </div>
  <div class="panel-footer">
    <%= link_to t("edit"), edit_admin_category_path(category),
      class: "btn btn-success" %>
    <%= link_to t("delete"), [:admin, category], method: :delete,
      data: {confirm: t("confirm")}, class: "btn btn-danger" %>
  </div>
</div>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: @category %>
  
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
  
  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide title: t("categories") %>
<% provide :button_text, t("category_update") %>
<h1><%= t "category_update" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<%= provide title: t("categories") %>
<div class="row">
  <h1><%= t "categories" %></h1>
  <div class="btn-group btn-group-justified form-group">
    <%= link_to t("category_new"), new_admin_category_path, {class: "btn
      btn-primary"} %>
  </div>
  <%= will_paginate %>
  <ul class="categories">
    <%= render @categories %>
  </ul>
  <%= will_paginate %>
</div>

app/views/admin/categories/new.html.erb
<% provide title: t("categories") %>
<% provide :button_text, t("category_new") %>
<h1><%= t "category_new" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<% provide title: @category.title %>
<% provide :button_text, t("finish") %>
<div class="row">
  <div class="col-md-6">
    <h3><%= t "category" %></h3>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= @category.title %>
      </div>
      <div class="panel-body">
        <div><%= @category.description %></div>
      </div>
    </div>
    <br />

    <h3><%= t "add_word" %></h3>
    <%= render "admin/words/form" %>
  </div>

  <div class="col-md-6">
    <h3><%= t "words" %></h3>
    <%= render @words %>
    <%= will_paginate @words %>
  </div>
</div>